name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Clean build artifacts
        run: rm -rf dist build *.egg-info

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # безопаснее через python -m
          python -m twine upload --skip-existing dist/*

      - name: Update GitHub release notes
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NOTES=$'Package published to PyPI successfully!\n\n## Installation\n```bash\npip install etcd-dynamic-config\n```'
          gh release edit "$GITHUB_REF_NAME" --notes "$NOTES"
